### ISSUE TITLE
Unable to load any of {libcudnn_ops.so.9.1.0 ...

### ISSUE THREAD

**Issue by awohsen** [oddlama/whisper-overlay#3]
I followed quick start and after everything was up, held the shortcut, and shortly after docker exited:
```
realtime-stt-server  | INFO Importing runtime
realtime-stt-server  | INFO Initializing RealtimeSTT...
realtime-stt-server  | INFO AudioToTextRecorder ready
realtime-stt-server  | INFO Starting server on 0.0.0.0:7007
realtime-stt-server  | INFO Server ready to accept connections
realtime-stt-server  | INFO 172.20.0.1:60502 Connected to client
realtime-stt-server  | INFO 172.20.0.1:60502 Client requested mode stream
realtime-stt-server  | INFO 172.20.0.1:60502 Acquiring lock
realtime-stt-server  | WARNING Audio queue size exceeds latency limit. Current size: 224. Discarding old audio chunks.
realtime-stt-server  | Traceback (most recent call last):
realtime-stt-server  |   File "/app/realtime-stt-server.py", line 124, in handle_client
realtime-stt-server  |     msg = recv_message(conn)
realtime-stt-server  |   File "/app/realtime-stt-server.py", line 36, in recv_message
realtime-stt-server  |     message_str = message_bytes.decode("utf-8")
realtime-stt-server  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 84: invalid continuation byte
realtime-stt-server  | ERROR 172.20.0.1:60502 Error handling client: 'utf-8' codec can't decode byte 0xec in position 84: invalid continuation byte
realtime-stt-server  | INFO 172.20.0.1:60502 Connection closed
realtime-stt-server  | Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
realtime-stt-server  | Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor
realtime-stt-server exited with code 139
```

**Comment by mathe00** [comment]
@awohsen I'm experiencing exactly the same issue with cuDNN. I hadn't noticed this issue and created a new, more detailed issue here => #4 

I've provided more context and information about my environment (Arch Linux with KDE Plasma 6.3+ on Wayland) as well as complete error logs. The fundamental error remains the same: the Docker container can't find the required cuDNN 9.1.0 libraries, while my system has a more recent version (9.8.0).

It seems to be a recurring problem. Hopefully with our two reports combined, we can get a solution.

**Comment by awohsen** [comment]
@mathe00 Hey I don't exactly remember but I believe this fixed my issue:
```yaml
services:
  realtime-stt-server:
    build:
      context: .
      target: gpu # or cpu
    image: realtime-stt-server
    container_name: realtime-stt-server
    volumes:
      - cache:/root/.cache
    ports:
      - "7007:7007"

    # if 'gpu' target
    deploy:
      resources:
        reservations:
          devices:
          - driver: cdi
            device_ids:
              - nvidia.com/gpu=all
            capabilities: [gpu]

volumes:
  cache:

```

**Comment by mathe00** [comment]
@awohsen Thanks for your suggestion! I tried your CDI configuration but it still didn't work with the CUDA/cuDNN errors.

However, I managed to get the basic functionality working by switching to CPU mode:

```yaml
services:
  realtime-stt-server:
    build:
      context: .
      target: cpu
    image: realtime-stt-server
    container_name: realtime-stt-server
    volumes:
      - cache:/root/.cache
    ports:
      - "7007:7007"
    environment:
      - WHISPER_MODEL=small

volumes:
  cache:
```

Now the voice recognition works and I can see my transcribed speech in the overlay, but there's still one problem: it doesn't actually type the text into any applications. The transcription appears correctly in the overlay window but doesn't get inserted into text editors, browsers, or any other app.

Is there an additional step needed to make whisper-overlay actually type the text it recognizes?

**Comment by mathe00** [comment]
@awohsen Thanks again for your help. Following up on my previous comment where the overlay works in CPU mode but doesn't type the text:

After further investigation, it seems the root cause for the lack of text input isn't directly within `whisper-overlay` itself, but rather in my Wayland environment (KDE Plasma 6.3.4 / KWin 6.3.4 / Qt 6.9.0 on Arch Linux).

The key finding is that my Wayland compositor (KWin) **does not seem to expose the `zwp_virtual_keyboard_v1` protocol**.

I confirmed this by:
1. Running `wayland-info | grep virtual_keyboard`, which returns nothing.
2. Trying to simulate input with `wtype` (e.g., `sleep 3 && wtype "test"`), which fails with the error: `Compositor does not support the virtual keyboard protocol`.

Since `whisper-overlay` relies on this specific protocol to simulate keyboard input under Wayland (as mentioned in the README), its absence explains why the transcription appears in the overlay but cannot be typed into other applications.

So, the current situation is:
- The original CUDA/cuDNN issue remains unsolved for me (CDI config didn't help).
- CPU mode works for transcription and displaying the overlay.
- The final text input fails due to the missing `zwp_virtual_keyboard_v1` protocol in my KWin/Wayland session.

This suggests the typing issue is likely a bug or configuration problem within KWin/Plasma on my setup, rather than a bug in `whisper-overlay`'s typing logic. I'll need to investigate further on the KDE/Arch side (checking KWin logs, looking for similar bug reports).

Just wanted to share this finding in case anyone else runs into the "overlay works but no typing" issue on a similar setup.
